AbbottProvider/Areas/Register/Models/InternalVM.cs
using DocumentManager.CrossCutting.ApplicationModel;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace DocumentManager.Areas.Register.Models
{
    public class InternalVM
    {
        [Required(ErrorMessage = "Campo requerido.")]
        [Display(Name = "Email *")]
        [EmailAddress(ErrorMessage = "Email inválido.")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Campo requerido.")]
        [Display(Name = "Contraseña *")]
        [DataType(DataType.Password)]
        [StringLength(15, MinimumLength = 7, ErrorMessage = "Debe tener entre 7 y 15 caracteres")]
        [RegularExpression(@"^(?=.*[0-9])(?=.*[!@@#$\\_.%^&*])[a-zA-Z0-9!@@#$\\_.%^&*]{7,15}$", ErrorMessage = "* Debe tener entre 7 y 15 caracteres.<br>* Debe contener al menos una letra mayúscula y una minúscula.<br>* Debe contener al menos un número.<br>* Debe contener un carácter especial.")]
        public string Password { get; set; }

        public PersonAM Person { get; set; }
    }
}

AbbottProvider/Areas/Register/Models/RegisterVM.cs
using DocumentManager.CrossCutting.ApplicationModel;
using System.ComponentModel.DataAnnotations;

namespace DocumentManager.Areas.Register.Models
{
    public class RegisterVM
    {

        [Required(ErrorMessage = "Campo requerido.")]
        [Display(Name = "Email *")]
        [EmailAddress(ErrorMessage = "Email inválido.")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Campo requerido.")]
        [Display(Name = "Contraseña *")]
        [DataType(DataType.Password)]
        [StringLength(15, MinimumLength = 7, ErrorMessage = "Debe tener entre 7 y 15 caracteres")]
        [RegularExpression(@"^(?=.*[0-9])(?=.*[!@@#$\\_.%^&*])[a-zA-Z0-9!@@#$\\_.%^&*]{7,15}$", ErrorMessage = "* Debe tener entre 7 y 15 caracteres.<br>* Debe contener al menos una letra mayúscula y una minúscula.<br>* Debe contener al menos un número.<br>* Debe contener un carácter especial.")]
        public string Password { get; set; }

        public PersonAM Person { get; set; }
    }
}

AbbottProvider/Areas/Register/Controllers/RegistersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DocumentManager.CrossCutting.ApplicationModel;
using DocumentManager.Areas.Identity.Models;
using DocumentManager.Areas.Register.Models;
using Domain.Business.BO;
using Domain.Business.Interface;
using Domain.Context;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;

namespace DocumentManager.Areas.Register.Controllers
{
    [Area("Register")]
    public class RegistersController : Controller
    {
        private readonly ILogger<RegistersController> logger;
        private readonly SignInManager<Users> singInManager;
        private readonly RoleManager<Role> roleManager;
        private readonly UserManager<Users> userManager;
        private readonly IIdentificationType IdTypeBO;
        private readonly IDepartment departmentBO;
        private readonly IPerson personBO;

        public RegistersController(DomainContext context, ILogger<RegistersController> log, UserManager<Users> userManag, SignInManager<Users> signInManag, RoleManager<Role> roleManag)
        {
            IdTypeBO = new IdentificationTypeBO(context);
            departmentBO = new DepartmentBO(context);
            personBO = new PersonBO(context);
            singInManager = signInManag;
            roleManager = roleManag;
            userManager = userManag;
            logger = log;
        }

        public IActionResult Index()
        {
            RegisterVM model = new RegisterVM();
            LoadInfo();

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Index(RegisterVM model)
        {
            LoadInfo();

            try
            {
                if (ModelState.IsValid)
                {
                    model.Person.IdState = 1;
                    model.Person.RegistrationDate = DateTime.Now;

                    var personId = personBO.Create(model.Person);

                    if (personId > 0)
                    {
                        Users user = new Users
                        {
                            Email = model.Email,
                            UserName = model.Email,
                            IdPerson = personId,
                            IdState = 1,
                            IsExternal = true,
                            PasswordChangeDate = DateTime.Now.AddDays(300)
                        };

                        var resultCreated = await userManager.CreateAsync(user);
                        var passwordResult = await userManager.AddPasswordAsync(user, model.Password);
                        var asignRol = await userManager.AddToRoleAsync(user, "Proveedor");
                        // string confirmToken = await userManager.GenerateEmailConfirmationTokenAsync(user);
                        // string tokenEncode = System.Web.HttpUtility.UrlEncode(confirmToken);

                        return RedirectToAction("Login", "Account", new { area = "Identity" });
                    }
                }
            }
            catch (Exception ex)
            {
                logger.LogError(ex, ex.Message + " - /Register/Index");
            }


            return View(model);
        }

        [HttpGet]
        public IActionResult Internal()
        {
            InternalVM model = new InternalVM();
            LoadInfo();

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Internal(InternalVM model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    model.Person.IdState = 1;
                    model.Person.RegistrationDate = DateTime.Now;

                    var personId = personBO.Create(model.Person);

                    if (personId > 0)
                    {
                        Users user = new Users
                        {
                            Email = model.Email,
                            UserName = model.Email,
                            IdPerson = personId,
                            IdState = 1,
                            IsExternal = false,
                            PasswordChangeDate = DateTime.Now.AddDays(300)
                        };

                        var resultCreated = await userManager.CreateAsync(user);
                        var passwordResult = await userManager.AddPasswordAsync(user, model.Password);
                        var asignRol = await userManager.AddToRoleAsync(user, "Supervisor");
                        // string confirmToken = await userManager.GenerateEmailConfirmationTokenAsync(user);
                        // string tokenEncode = System.Web.HttpUtility.UrlEncode(confirmToken);

                        return RedirectToAction("InternalLogin", "Account", new { area = "Identity" });
                    }
                }
            }
            catch (Exception ex)
            {
                logger.LogError(ex, ex.Message + " - /Register/Internal");
            }

            return View(model);

        }

        private void LoadInfo()
        {
            try
            {
                var depart = departmentBO.Get();

                ViewBag.ListIdType = new SelectList(IdTypeBO.Get(), "Id", "Name");
                ViewBag.ListDepartment = new SelectList(depart, "Id", "Name");
                ViewBag.ListCities = new SelectList(new List<CityAM>(), "Id", "Name");
                ViewBag.ListDep = new SelectList(depart, "Id", "Name");
                ViewBag.ListCity = new SelectList(new List<CityAM>(), "Id", "Name");
            }
            catch (Exception ex)
            {
                logger.LogError(ex, ex.Message + " - Register/Register/LoadInfo");
            }


        }
    }
}

AbbottProvider/Areas/Register/Views/Registers/Index.cshtml
@model DocumentManager.Areas.Register.Models.RegisterVM
@{
    ViewData["Title"] = "Register";
    Layout = "_layout.cshtml";
}

<div class="">
    <div class="login-logo">
        <a href="/Identity/Account/Login"><b>Gestor</b>documental</a>
    </div>
    <!-- /.login-logo -->
    <div class="card">
        <div class="row col-lg-12 col-12">
            <div class="card-body login-card-body">
                <form asp-area="Register" asp-controller="Registers" asp-action="Index" method="POST" enctype="multipart/form-data">
                    <div class="row">
                        <div class="form-group col-md-6">
                            @Html.LabelFor(m => m.Person.Name)
                            @Html.TextBoxFor(m => m.Person.Name, new { @class = "form-control", placeholder = "Nombre" })
                            @Html.ValidationMessageFor(m => m.Person.Name, "", new { @class = "" })
                        </div>
                        <div class="form-group col-md-6">
                            @Html.LabelFor(m => m.Person.SecondName)
                            @Html.TextBoxFor(m => m.Person.SecondName, new { @class = "form-control", placeholder = "Segundo nombre" })
                            @Html.ValidationMessageFor(m => m.Person.SecondName, "", new { @class = "" })
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group col-md-6">
                            @Html.LabelFor(m => m.Person.SurName)
                            @Html.TextBoxFor(m => m.Person.SurName, new { @class = "form-control", placeholder = "Apellido" })
                            @Html.ValidationMessageFor(m => m.Person.SurName, "", new { @class = "" })
                        </div>
                        <div class="form-group col-md-6">
                            @Html.LabelFor(m => m.Person.SecondSurName)
                            @Html.TextBoxFor(m => m.Person.SecondSurName, new { @class = "form-control" })
                            @Html.ValidationMessageFor(m => m.Person.SecondSurName, "", new { @class = "" })
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group col-md-6">
                            @Html.LabelFor(m => m.Person.IdIdentificationType)
                            @Html.DropDownListFor(m => m.Person.IdIdentificationType, (IEnumerable<SelectListItem>)ViewBag.ListIdType, "Seleccione", new { @class = "form-control" })
                            @Html.ValidationMessageFor(m => m.Person.IdIdentificationType, "", new { @class = "" })
                        </div>
                        <div class="form-group col-md-6">
                            @Html.LabelFor(m => m.Person.Identification)
                            @Html.TextBoxFor(m => m.Person.Identification, new { @class = "form-control" })
                            @Html.ValidationMessageFor(m => m.Person.Identification, "", new { @class = "" })
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group col-md-6">
                            @Html.LabelFor(m => m.Person.IdDepartPlace)
                            @Html.DropDownListFor(m => m.Person.IdDepartPlace, (IEnumerable<SelectListItem>)ViewBag.ListDepartment, "Seleccione", new { @class = "form-control" })
                        </div>
                        <div class="form-group col-md-6">
                            @Html.LabelFor(m => m.Person.Birthplace)
                            @Html.DropDownListFor(m => m.Person.Birthplace, (IEnumerable<SelectListItem>)ViewBag.ListCities, "Seleccione", new { @class = "form-control" })
                            @Html.ValidationMessageFor(m => m.Person.Birthplace, "", new { @class = "" })
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group">
                            @Html.LabelFor(m => m.Person.Birthdate)
                            @Html.TextBoxFor(m => m.Person.Birthdate, new { @class = "form-control" })
                            @Html.ValidationMessageFor(m => m.Person.Birthdate, "", new { @class = "" })
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group col-md-6">
                            @Html.LabelFor(m => m.Person.Phone)
                            @Html.TextBoxFor(m => m.Person.Phone, new { @class = "form-control", placeholder = "usuario@mail.com" })
                            @Html.ValidationMessageFor(m => m.Person.Phone, "", new { @class = "" })
                        </div>
                        <div class="form-group col-md-6">
                            @Html.LabelFor(m => m.Person.Cellphone)
                            @Html.TextBoxFor(m => m.Person.Cellphone, new { @class = "form-control" })
                            @Html.ValidationMessageFor(m => m.Person.Cellphone, "", new { @class = "" })
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group col-md-6">
                            @Html.LabelFor(m => m.Person.IdDepartment)
                            @Html.DropDownListFor(m => m.Person.IdDepartment, (IEnumerable<SelectListItem>)ViewBag.ListDep, "Seleccione", new { @class = "form-control" })
                        </div>
                        <div class="form-group col-md-6">
                            @Html.LabelFor(m => m.Person.IdCity)
                            @Html.DropDownListFor(m => m.Person.IdCity, (IEnumerable<SelectListItem>)ViewBag.ListCity, "Seleccione", new { @class = "form-control" })
                            @Html.ValidationMessageFor(m => m.Person.IdCity, "", new { @class = "" })
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group col-md-6">
                            @Html.LabelFor(m => m.Person.Address)
                            @Html.TextBoxFor(m => m.Person.Address, new { @class = "form-control" })
                            @Html.ValidationMessageFor(m => m.Person.Address, "", new { @class = "" })
                        </div>
                    </div>
                    <hr />
                    <p class="text-center">Datos de usuario</p>
                    <div class="form-group">
                        @Html.LabelFor(m => m.Email)
                        @Html.TextBoxFor(m => m.Email, new { @class = "form-control", placeholder = "usuario@mail.com" })
                        @Html.ValidationMessageFor(m => m.Email, "", new { @class = "" })
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(m => m.Password)
                        @Html.PasswordFor(m => m.Password, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.Password, "", new { @class = "" })
                    </div>

                    <button type="submit" class="btn btn-primary">Crear</button>
                </form>

            </div>
            <!-- /.login-card-body -->
        </div>

    </div>
</div>

@section Scripts{
    <script src="~/js/Register/register.js"></script>
 }

AbbottProvider/Areas/Register/Views/Registers/Internal.cshtml
@model DocumentManager.Areas.Register.Models.InternalVM
@{
    ViewData["Title"] = "Register";
    Layout = "_layout.cshtml";
}

<div class="">
    <div class="login-logo">
        <a href="/Identity/Account/Login"><b>Gestor</b>documental</a>
    </div>
    <!-- /.login-logo -->
    <div class="card">
        <div class="row col-lg-12 col-12">
            <div class="card-body login-card-body">
                <form asp-area="Register" asp-controller="Registers" asp-action="Internal" method="POST" enctype="multipart/form-data">
                    <div class="row">
                        <div class="form-group col-md-6">
                            @Html.LabelFor(m => m.Person.Name)
                            @Html.TextBoxFor(m => m.Person.Name, new { @class = "form-control", placeholder = "Nombre" })
                            @Html.ValidationMessageFor(m => m.Person.Name, "", new { @class = "" })
                        </div>
                        <div class="form-group col-md-6">
                            @Html.LabelFor(m => m.Person.SecondName)
                            @Html.TextBoxFor(m => m.Person.SecondName, new { @class = "form-control", placeholder = "Segundo nombre" })
                            @Html.ValidationMessageFor(m => m.Person.SecondName, "", new { @class = "" })
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group col-md-6">
                            @Html.LabelFor(m => m.Person.SurName)
                            @Html.TextBoxFor(m => m.Person.SurName, new { @class = "form-control", placeholder = "Apellido" })
                            @Html.ValidationMessageFor(m => m.Person.SurName, "", new { @class = "" })
                        </div>
                        <div class="form-group col-md-6">
                            @Html.LabelFor(m => m.Person.SecondSurName)
                            @Html.TextBoxFor(m => m.Person.SecondSurName, new { @class = "form-control" })
                            @Html.ValidationMessageFor(m => m.Person.SecondSurName, "", new { @class = "" })
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group col-md-6">
                            @Html.LabelFor(m => m.Person.IdIdentificationType)
                            @Html.DropDownListFor(m => m.Person.IdIdentificationType, (IEnumerable<SelectListItem>)ViewBag.ListIdType, "Seleccione", new { @class = "form-control" })
                            @Html.ValidationMessageFor(m => m.Person.IdIdentificationType, "", new { @class = "" })
                        </div>
                        <div class="form-group col-md-6">
                            @Html.LabelFor(m => m.Person.Identification)
                            @Html.TextBoxFor(m => m.Person.Identification, new { @class = "form-control" })
                            @Html.ValidationMessageFor(m => m.Person.Identification, "", new { @class = "" })
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group col-md-6">
                            @Html.LabelFor(m => m.Person.IdDepartPlace)
                            @Html.DropDownListFor(m => m.Person.IdDepartPlace, (IEnumerable<SelectListItem>)ViewBag.ListDepartment, "Seleccione", new { @class = "form-control" })
                        </div>
                        <div class="form-group col-md-6">
                            @Html.LabelFor(m => m.Person.Birthplace)
                            @Html.DropDownListFor(m => m.Person.Birthplace, (IEnumerable<SelectListItem>)ViewBag.ListCities, "Seleccione", new { @class = "form-control" })
                            @Html.ValidationMessageFor(m => m.Person.Birthplace, "", new { @class = "" })
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group">
                            @Html.LabelFor(m => m.Person.Birthdate)
                            @Html.TextBoxFor(m => m.Person.Birthdate, new { @class = "form-control" })
                            @Html.ValidationMessageFor(m => m.Person.Birthdate, "", new { @class = "" })
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group col-md-6">
                            @Html.LabelFor(m => m.Person.Phone)
                            @Html.TextBoxFor(m => m.Person.Phone, new { @class = "form-control", placeholder = "usuario@mail.com" })
                            @Html.ValidationMessageFor(m => m.Person.Phone, "", new { @class = "" })
                        </div>
                        <div class="form-group col-md-6">
                            @Html.LabelFor(m => m.Person.Cellphone)
                            @Html.TextBoxFor(m => m.Person.Cellphone, new { @class = "form-control" })
                            @Html.ValidationMessageFor(m => m.Person.Cellphone, "", new { @class = "" })
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group col-md-6">
                            @Html.LabelFor(m => m.Person.IdDepartment)
                            @Html.DropDownListFor(m => m.Person.IdDepartment, (IEnumerable<SelectListItem>)ViewBag.ListDep, "Seleccione", new { @class = "form-control" })
                        </div>
                        <div class="form-group col-md-6">
                            @Html.LabelFor(m => m.Person.IdCity)
                            @Html.DropDownListFor(m => m.Person.IdCity, (IEnumerable<SelectListItem>)ViewBag.ListCity, "Seleccione", new { @class = "form-control" })
                            @Html.ValidationMessageFor(m => m.Person.IdCity, "", new { @class = "" })
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group col-md-6">
                            @Html.LabelFor(m => m.Person.Address)
                            @Html.TextBoxFor(m => m.Person.Address, new { @class = "form-control" })
                            @Html.ValidationMessageFor(m => m.Person.Address, "", new { @class = "" })
                        </div>
                    </div>
                    <hr />
                    <p class="text-center">Datos de usuario</p>
                    <div class="form-group">
                        @Html.LabelFor(m => m.Email)
                        @Html.TextBoxFor(m => m.Email, new { @class = "form-control", placeholder = "usuario@mail.com" })
                        @Html.ValidationMessageFor(m => m.Email, "", new { @class = "" })
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(m => m.Password)
                        @Html.PasswordFor(m => m.Password, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.Password, "", new { @class = "" })
                    </div>

                    <button type="submit" class="btn btn-primary">Crear</button>
                </form>

            </div>
            <!-- /.login-card-body -->
        </div>

    </div>
</div>

@section Scripts{
    <script src="~/js/Register/register.js"></script>
}

AbbottProvider/Areas/Register/Views/Registers/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>AdminLTE 3 | Log in</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/lib/fontawesome-free/css/all.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- icheck bootstrap -->
    <link rel="stylesheet" href="~/lib/icheck-bootstrap/icheck-bootstrap.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/css/adminlte.min.css">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>
<body class="hold-transition login-page">

    @RenderBody()

    <!-- /.login-box -->
    <!-- jQuery -->
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <!-- Bootstrap 4 -->
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <!-- AdminLTE App -->
    <script src="~/js/adminlte.min.js"></script>

    @RenderSection("Scripts", required: false)

</body>
</html>